[package]
name = "deck/cloud-empire"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Trove = "sleitnick/trove@1.8.0"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"